apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:  
  name: hello-pipeline
spec:
  params:
    - name: message
  tasks:
    - name: hello
      taskRef:
        name: echo
      params:
        - name: message
          value: "$(params.message)"

---

apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:  
  name: cd-pipeline

spec:
  params:
    - name: repo-url
    - name: branch
      default: "master"
  tasks:
    - name: clone
      taskRef:
        name: checkout
      params:
      - name: repo-url
        value: "$(params.repo-url)"
      - name: branch
        value: "$(params.branch)"
    - name: lint
      taskRef:
        name: echo
      params:
      - name: message
        value: "Chamando o linter Flake8..."
      runAfter:
        - clone
    - name: tests
      taskRef:
        name: echo
      params:
      - name: message
        value: "Executando testes de unidade com PyUnit..."
      runAfter:
        - lint
    - name: build
      taskRef:
        name: echo
      params:
      - name: message
        value: "Construindo imagem para $(params.repo-url) ..."
      runAfter:
        - tests
